// ============================================================
// PORTFOLIO DATA – juergennigg.com
// Kategorien: artwork | fashion | portrait | reise | landschaft | sport
// Reihenfolge: nach farblicher Passung (dunkel → B&W → kühl → warm → farbe → clean)
// ============================================================

const portfolioItems = [

    // ── DUNKEL / SCHWARZ ─────────────────────────────────────

    { id:1,  cat:"landschaft", title:"Nockspitze Cross",    subtitle:"B&W · Night",           image:"assets/img/portfolio/juergen-nigg-nockspitze-summit-cross-night-fog-tyrol.jpg",          description:"Summit cross on the Nockspitze at night. Fog and moonlight conspire to erase the figure standing at its base — the shape barely human, barely there.", client:"Private Project", date:"07-21", gridRowSpan:44 },
    { id:2,  cat:"artwork",    title:"2ONE",                subtitle:"Artwork",                image:"assets/img/portfolio/juergen-nigg-artwork-2one-portrait-series.jpg",                       description:"A fierce Mouth - seductive Lips,\nattributes to be rich.\n\nThunderous - inverse to her tone,\ncaught in a triangle of monochrome.\n\nStanding in blue, labeled - but not true.\nNaked below. a Human.\n\nVulnerable.\n\nSeries: Where do we go, where do we come from.\nPrint / Hahnemühle Fine Art Baryta / 60x90cm", client:"Private Project", date:"04-20", gridRowSpan:38 },
    { id:3,  cat:"portrait",   title:"Lips & Hat",          subtitle:"Portrait",               image:"assets/img/portfolio/juergen-nigg-portrait-hat-shadow-lowkey.jpg",         description:"Studio portrait study in dramatic low key light. Hat, shadow, skin — reduced to the essential.", client:"Private Project", date:"04-22", gridRowSpan:40 },
    { id:4,  cat:"sport",      title:"Minimal Laax",        subtitle:"Sports · Experimental",  image:"assets/img/portfolio/juergen-nigg-skiing-laax-bw-diptych-minimal.jpg",               description:"Two skiers, two worlds — day and night, positive and negative. A diptych compressed into one frame: one figure on white powder, one on absolute black.", client:"Private Project", date:"03-21", gridRowSpan:40 },
    { id:5,  cat:"artwork",    title:"Super(ri)or",         subtitle:"Artwork",                image:"assets/img/portfolio/juergen-nigg-artwork-superior-nature-bubbles.jpg",                   description:"When taking a close look how society treats our surroundings, it is quite interesting that humans seem to feel superior to nature itself. Imagine that we are just bubbles in an aquarium which try to reach the surface.\n\nNature's unwritten law is balance, nothing is superior.\n\nI guess balance hurts, as we all are just shadows, which need the sun to shine...\n\nSeries: Where do we go, where do we come from.", client:"Private Project", date:"05-21", gridRowSpan:44 },
    { id:6,  cat:"artwork",    title:"Spirit",              subtitle:"Art · Venice",           image:"assets/img/portfolio/juergen-nigg-venice-biennale-spirit-text-wall-art.jpg",     description:"\"When I look at you my spirit leaves my body.\"\n\nA sentence painted onto a dark wall at the Venice Biennale — hand prints in red clay surrounding it. Text as confessional. Presence as vulnerability.", client:"Private Project", date:"06-22", gridRowSpan:34 },
    { id:7,  cat:"artwork",    title:"Digital Distraction", subtitle:"Artwork",                image:"assets/img/portfolio/juergen-nigg-artwork-digital-distraction-series.jpg",          description:"Half way sick, but still hooked.\n\nThe digital revolution made it more or less secretly socially acceptable. Disturbing content is all over the internet. By now, approximately half the world's population is connected and influenced by it.\n\nWhat is real?\n\nSeries: Where do we go, where do we come from.\nPrint / Hahnemühle Fine Art Baryta / 50x75cm", client:"Private Project", date:"03-20", gridRowSpan:42 },
    { id:8,  cat:"sport",      title:"X-Games",             subtitle:"Sports",                 image:"assets/img/portfolio/juergen-nigg-xgames-norway-motox-corey-creed.jpg",                      description:"At X-Games Norway, I was on site to shoot a documentary about an upcoming athlete. As the light improved, I captured a moment where Corey Creed sent his bike soaring high enough to nearly meet the rooftop.", client:"Private", date:"08-19", gridRowSpan:36 },

    // ── B&W / MINIMAL ────────────────────────────────────────

    { id:9,  cat:"reise",      title:"Rock Silhouette",     subtitle:"B&W · Sardinia",         image:"assets/img/portfolio/juergen-nigg-sardinia-sea-stack-rock-silhouette-bw.jpg",   description:"A sea stack off the Sardinian coast reduced to pure form — black mass, white sky, silver water. Everything unnecessary removed by overexposure. What remains is enough.", client:"Private Project", date:"09-23", gridRowSpan:32 },
    { id:10, cat:"reise",      title:"Venice Canal",        subtitle:"B&W · Travel",           image:"assets/img/portfolio/juergen-nigg-venice-grand-canal-bridge-silhouette-bw.jpg",       description:"A Grand Canal bridge reduced to silhouette at dusk. The water carries the last light between the buildings — the city's geometry in its simplest possible statement.", client:"Private Project", date:"06-22", gridRowSpan:36 },
    { id:11, cat:"landschaft", title:"Wipptal",             subtitle:"B&W · Landscape",        image:"assets/img/portfolio/juergen-nigg-wipptal-winter-mountain-bw-tyrol-alps.jpg",                description:"A winter ascent in the Wipptal. The snowfield catches the angle of morning light and divides the frame — half shadow, half form. The mountain indifferent to the cold.", client:"Private Project", date:"02-21", gridRowSpan:34 },
    { id:12, cat:"landschaft", title:"Nockspitze Moon",     subtitle:"B&W · Night",            image:"assets/img/portfolio/juergen-nigg-nockspitze-mountain-moon-night-bw-stars.jpg",             description:"Full moon over the Nockspitze ridge. Clouds stream past the summit in long exposure — the mountain silhouette sharp against a brightened sky filled with barely visible stars.", client:"Private Project", date:"07-21", gridRowSpan:38 },
    { id:13, cat:"landschaft", title:"CrankIt Mountains",   subtitle:"B&W · Landscape",        image:"assets/img/portfolio/juergen-nigg-zugspitze-storm-clouds-mountain-bw.jpg",           description:"Storm light over the Zugspitz massif. The clouds press down on the peaks and a ray of sun cuts through — the Alps in their most dramatic and uncompromising mood.", client:"Private Project", date:"04-19", gridRowSpan:36 },
    { id:14, cat:"landschaft", title:"Rinnenspitze",        subtitle:"B&W · Landscape",        image:"assets/img/portfolio/juergen-nigg-habicht-north-face-clouds-bw-alps-tyrol.jpg",             description:"The north face of the Habicht, shot from the Rinnenspitze approach. Clouds breach the ridge in a single powerful mass — the scale of the mountain readable only by the tiny snow couloirs threaded between the rocks.", client:"Private Project", date:"08-24", gridRowSpan:42 },
    { id:15, cat:"sport",      title:"Umbrella",            subtitle:"Sports · B&W",           image:"assets/img/portfolio/juergen-nigg-krimml-waterfall-umbrella-bw-austria.jpg",             description:"Two people shelter beneath an umbrella at the base of the Krimmler Wasserfälle. The waterfall spray fills the sky behind them — a wall of white noise, of water becoming air. The umbrella a small, stubborn gesture against the impossible.", client:"Private Project", date:"09-21", gridRowSpan:40 },
    { id:16, cat:"sport",      title:"Ski B&W",             subtitle:"Sports",                 image:"assets/img/portfolio/juergen-nigg-freeride-skiing-powder-bw-alps.jpg",         description:"High-speed turn through a steep mogul field. Snow explodes upward in every direction — the skier's form compressed into the moment before the next drop.", client:"Private Project", date:"04-25", gridRowSpan:38 },
    { id:17, cat:"artwork",    title:"Prejudice",           subtitle:"Artwork",                image:"assets/img/portfolio/juergen-nigg-artwork-prejudice-portrait-series.jpg",                   description:"We learn - we judge.\n\nCan you hear,\nthe voice inside?\n\nIt's hard to catch?\nIts drowned in teachings?\n\nThat's trust been taken,\nand prejudice awaken.\n\nSeries: Where do we go, where do we come from.\nPrint / Hahnemühle Fine Art Baryta / 50x75cm", client:"Private Project", date:"03-21", gridRowSpan:36 },

    // ── KÜHL / BLAU ──────────────────────────────────────────

    { id:18, cat:"reise",      title:"Malta",               subtitle:"Travel",                 image:"assets/img/portfolio/juergen-nigg-malta-blue-hour-cityscape-long-exposure.jpg",       description:"Blue hour in Malta. Capturing the city's golden lights as they bleed into the deep indigo of the Mediterranean. It's a delicate balancing act of long exposure — finding that perfect shutter speed to turn the ocean into a mirror.", client:"Private Project", date:"11-17", gridRowSpan:30 },
    { id:19, cat:"landschaft", title:"Patscherkofel",       subtitle:"Landscape",              image:"assets/img/portfolio/juergen-nigg-patscherkofel-fog-innsbruck-valley-winter.jpg",           description:"Above the Innsbruck cloud inversion at dusk. The Inn valley disappears beneath a grey sea of fog while the peaks emerge snow-white into clear air — the city invisible below.", client:"Private Project", date:"01-19", gridRowSpan:32 },
    { id:20, cat:"reise",      title:"Achensee",            subtitle:"Aerial · Travel",        image:"assets/img/portfolio/juergen-nigg-achensee-aerial-sailing-boats-tyrol.jpg",          description:"Achensee from altitude. Sailboats scattered across deep emerald water like brushstrokes — the campsite and forest below sharply real, the lake an abstraction of colour.", client:"Private Project", date:"08-20", gridRowSpan:38 },
    { id:21, cat:"reise",      title:"Paraglider",          subtitle:"Aerial · Travel",        image:"assets/img/portfolio/juergen-nigg-paraglider-achensee-aerial-tyrol-austria.jpg",        description:"From the summit of Rotspitze, looking straight down onto the turquoise shallows of Achensee. A paraglider traces a slow arc above the water — freedom reduced to a dot against the vast geometry of land and lake.", client:"Private Project", date:"08-20", gridRowSpan:40 },
    { id:22, cat:"artwork",    title:"Biennale Neon",       subtitle:"Art · Venice",           image:"assets/img/portfolio/juergen-nigg-venice-biennale-neon-wire-installation.jpg",       description:"An installation at the Venice Biennale — blue neon wire suspended in stacked geometric planes. Architecture as suggestion, space as medium. The work exists only in the dark.", client:"Private Project", date:"06-22", gridRowSpan:36 },

    // ── WARM / GOLDEN ────────────────────────────────────────

    { id:23, cat:"landschaft", title:"Salfeins Lake",       subtitle:"Landscape",              image:"assets/img/portfolio/juergen-nigg-salfeins-alpine-lake-sunset-reflection-tyrol.jpg",        description:"Last light at the high alpine lake above Salfeins. A lone signpost stands in silhouette at the water's edge — its reflection perfect in the still surface, the mountains behind burning orange then gone.", client:"Private Project", date:"09-25", gridRowSpan:36 },
    { id:24, cat:"landschaft", title:"Salfeins Overlook",   subtitle:"Landscape",              image:"assets/img/portfolio/juergen-nigg-salfeins-innsbruck-valley-sunset-silhouette.jpg",           description:"Sunset from the ridge above Salfeins. A figure stands on the last rock before the world drops away into the Inn valley and Innsbruck below — the sun already behind the western peaks.", client:"Private Project", date:"09-25", gridRowSpan:38 },
    { id:25, cat:"landschaft", title:"Innsbruck Storm",     subtitle:"Urban · Landscape",      image:"assets/img/portfolio/juergen-nigg-innsbruck-sahara-dust-amber-dramatic-sky.jpg",              description:"A Saharan dust event turns the Innsbruck sky to amber. The Maria-Theresien-Strasse stretches into the glow, the Nordkette invisible behind the haze — the city under a light it has never quite seen before.", client:"Private Project", date:"08-24", gridRowSpan:40 },
    { id:26, cat:"reise",      title:"Sardinia Sunset",     subtitle:"Travel",                 image:"assets/img/portfolio/juergen-nigg-sardinia-coastal-sunset-silhouette.jpg",                description:"The last light dissolves into the Sardinian coastline. Silhouettes of rock and pine frame the glowing horizon — a moment that lasts seconds but stays forever.", client:"Private Project", date:"09-23", gridRowSpan:32 },
    { id:27, cat:"landschaft", title:"Father & Son",        subtitle:"Experimental",           image:"assets/img/portfolio/juergen-nigg-father-son-tree-sunset-minimal.jpg",                        description:"The image shows two trees of different sizes in front of a sunset. The larger tree represents a father's guiding presence — standing behind the smaller tree not to shield it from the world, but to support and help it overcome challenges.", client:"Private Project", date:"01-21", gridRowSpan:34 },
    { id:28, cat:"reise",      title:"Sardinia Summit",     subtitle:"Travel",                 image:"assets/img/portfolio/juergen-nigg-sardinia-mountain-summit-golden-hour.jpg",                description:"First light on the summit ridge above the Gallura coast. Ancient rock, worn stone steps and a brass instrument surveying the sea — Sardinia at its most elemental.", client:"Private Project", date:"09-23", gridRowSpan:36 },
    { id:29, cat:"reise",      title:"Ethiopia Watcher",    subtitle:"Travel",                 image:"assets/img/portfolio/juergen-nigg-ethiopia-highlands-morning-landscape-watcher.jpg",          description:"Early morning on the Ethiopian highlands. A lone figure crouched against the vast horizon — the moment before the mist lifts and the world comes into focus.", client:"Private Project", date:"11-18", gridRowSpan:34 },
    { id:30, cat:"sport",      title:"CrankIt",             subtitle:"Sports",                 image:"assets/img/portfolio/juergen-nigg-crankit-skiing-park-ehrwald-tyrol.jpg", description:"Back in 2019, Lucas Mangold launched a gathering in Ehrwald to celebrate the soul of skiing. With the mood 'Crank It' to the max, it's all about good people, easy vibes, and pure park shredding.", client:"Private Project", date:"04-19", gridRowSpan:30 },

    // ── ERDTÖNE / REISE ──────────────────────────────────────

    { id:31, cat:"reise",      title:"Ethiopia",            subtitle:"Travel",                 image:"assets/img/portfolio/juergen-nigg-ethiopia-simien-mountains-cloud-forest.jpg",       description:"Deep in the Simien Mountains highlands, the world disappears into a thick, rolling fog. The ancient trees are draped in heavy layers of hanging moss, a living testament to the purity of the air at this altitude.", client:"Private Project", date:"04-19", gridRowSpan:36 },
    { id:32, cat:"reise",      title:"Ranger",              subtitle:"Travel",                 image:"assets/img/portfolio/juergen-nigg-ethiopia-simien-mountains-ranger.jpg",       description:"On the rugged precipice of Ethiopia's Simien Mountains, a local ranger stands sentinel. Perched on the literal edge of the world, he surveys the vast, jagged highlands with his rifle slung over his shoulder — a silent guardian of one of Africa's most dramatic landscapes.", client:"Private Project", date:"11-18", gridRowSpan:36 },
    { id:33, cat:"reise",      title:"Sardinia Cliffs",     subtitle:"Travel",                 image:"assets/img/portfolio/juergen-nigg-sardinia-capo-caccia-cliffs-blue-sea.jpg",                description:"Looking down the spine of Capo Caccia from the ridge trail. Deep cobalt sea, white limestone and the rust-red soil of the path — three colours that define the island.", client:"Private Project", date:"09-23", gridRowSpan:40 },
    { id:34, cat:"reise",      title:"Building Bridges",    subtitle:"Travel",                 image:"assets/img/portfolio/juergen-nigg-venice-building-bridges-quinn-sculpture.jpg",       description:"Looking up at Lorenzo Quinn's 'Building Bridges' from the waterline of the Arsenale. Each arch represents a core value — Friendship, Wisdom, Help, Faith, Hope, and Love — creating a rhythmic canopy against the Venetian sky.", client:"Private Project", date:"10-19", gridRowSpan:34 },
    { id:35, cat:"reise",      title:"Sunrise",             subtitle:"Travel",                 image:"assets/img/portfolio/juergen-nigg-sardinia-caprera-lighthouse-sunrise.jpg", description:"While exploring Sardinia in 2023, I hiked through the coastal ruins of Isola di Caprera. I managed to capture an incredible sunrise that lined up perfectly with the lighthouse on Isolotto di Barrettini.", client:"Private Project", date:"09-23", gridRowSpan:30 },
    { id:36, cat:"reise",      title:"Swan",                subtitle:"Travel · Documentary",   image:"assets/img/portfolio/juergen-nigg-swan-rusty-bridge-pier-gdansk-poland.jpg",           description:"A white swan glides beneath the rusted skeleton of an abandoned bridge pier. Grace and decay — an unremarkable scene that reveals itself only to those who stop.", client:"Private Project", date:"08-24", gridRowSpan:42 },
    { id:37, cat:"artwork",    title:"Archive",             subtitle:"Art · Venice",           image:"assets/img/portfolio/juergen-nigg-venice-biennale-paper-archive-light.jpg",     description:"Thousands of documents cover the floor of a darkened pavilion at the Venice Biennale. A single shaft of light enters from above — the archive breathing, the past made present.", client:"Private Project", date:"06-22", gridRowSpan:38 },
    { id:38, cat:"landschaft", title:"Riezer Reflection",   subtitle:"Alps · Austria",         image:"assets/img/portfolio/juergen-nigg-riezerferner-alpine-lake-reflection-autumn.jpg",           description:"A perfect mirror at the high alpine lake on Riezerferners. The mountain reflected in still water, autumn grass at the water's edge — symmetry earned only by arriving early enough.", client:"Private Project", date:"10-24", gridRowSpan:34 },

    // ── FARBE / LEBENDIG ─────────────────────────────────────

    { id:39, cat:"portrait",   title:"Portrait Colour",     subtitle:"Portrait",               image:"assets/img/portfolio/juergen-nigg-portrait-colour-paint-ethiopia.jpg",            description:"Identity, colour and intensity. Face paint meets Ethiopian textile tradition in a raw, unfiltered moment of presence.", client:"Private Project", date:"06-19", gridRowSpan:42 },
    { id:40, cat:"reise",      title:"Burano Ladder",       subtitle:"Travel",                 image:"assets/img/portfolio/juergen-nigg-burano-venice-colourful-facade-ladder.jpg",        description:"Geometry and colour in a Burano side alley. A moment of stillness caught between fading paint, a leaning ladder and a woman resting in the shade — the island in its most honest state.", client:"Private Project", date:"06-22", gridRowSpan:38 },
    { id:41, cat:"reise",      title:"Burano",              subtitle:"Travel",                 image:"assets/img/portfolio/juergen-nigg-burano-venice-pink-minimal-travel.jpg",                     description:"Known for its exquisite lace craftsmanship and vibrant, colorful houses, Burano is a must-visit when traveling to Venice. After seeing the first magical façade, I felt inspired to create a minimalist series that captures the island's unique charm.", client:"Private Project", date:"06-22", gridRowSpan:32 },
    { id:42, cat:"landschaft", title:"Autumn",              subtitle:"Urban · Landscape",      image:"assets/img/portfolio/juergen-nigg-innsbruck-autumn-virginia-creeper-villa.jpg",                  description:"An Innsbruck villa smothered in Virginia creeper at peak colour. Through the black branches a single window holds the light — the house consumed by autumn, barely itself anymore.", client:"Private Project", date:"10-21", gridRowSpan:36 },
    { id:43, cat:"sport",      title:"Carousel",            subtitle:"Travel · Night",         image:"assets/img/portfolio/juergen-nigg-carousel-long-exposure-night-gdansk.jpg",      description:"Long-exposure of a fairground carousel in Gdańsk at night. Light trails spiral outward from the hub — the ride long finished, its movement preserved in gold.", client:"Private Project", date:"08-24", gridRowSpan:38 },

    // ── FASHION / CLEAN ──────────────────────────────────────

    { id:44, cat:"fashion",    title:"Aster Red Chairs",    subtitle:"Fashion",                image:"assets/img/portfolio/juergen-nigg-aster-leather-bag-red-botanical-garden.jpg",           description:"Aster leather bag in motion — the red of the bag and the red of the park chairs in dialogue. A casual, sun-drenched moment on the edge of something.", client:"Aster", date:"08-22", gridRowSpan:38 },
    { id:45, cat:"fashion",    title:"Jungle Fever",        subtitle:"Fashion",                image:"assets/img/portfolio/juergen-nigg-aster-jungle-fever-botanical-garden.jpg", description:"Sabrina Huber for Aster Leather Bags. This session in the botanical gardens features the 'Biggie' in Creme, styled against a bold camouflage dress. The lush palms provide a vivid backdrop, creating a striking color harmony.", client:"Aster", date:"08-22", gridRowSpan:40 },
    { id:46, cat:"fashion",    title:"Inn Beach",           subtitle:"Fashion",                image:"assets/img/portfolio/juergen-nigg-aster-leather-bag-inn-river-innsbruck.jpg",          description:"Aster Leather Bags at the banks of the Inn river. The Burgundy tote against alpine light — a study in contrast between urban craft and natural setting.", client:"Aster", date:"04-24", gridRowSpan:40 },
    { id:47, cat:"reise",      title:"Sardinia Column",     subtitle:"Travel",                 image:"assets/img/portfolio/juergen-nigg-sardinia-roman-column-sailboat-sea.jpg",               description:"An ancient Roman column stands alone against the Sardinian sky. A single sailboat crosses the horizon — past and present sharing the same sea.", client:"Private Project", date:"09-23", gridRowSpan:38 },
    { id:48, cat:"fashion",    title:"Studio",              subtitle:"Fashion",                image:"assets/img/portfolio/juergen-nigg-aster-studio-fashion-portrait.jpg", description:"Verena Pötzl x Aster Leather Bags. A professional studio shoot highlighting the elegance of everyday utility.\n\nDiscover the range of premium leather bags at YourAster.com", client:"Aster", date:"06-23", gridRowSpan:38 },
    { id:49, cat:"fashion",    title:"Aster",               subtitle:"Fashion",                image:"assets/img/portfolio/juergen-nigg-aster-leather-bag-fashion-commercial.jpg",                      description:"Your Aster is a brand dedicated to handcrafted leather bags made in Ethiopia. Rooted in Ethiopian heritage, the founder brings a deep personal connection to the country and its craftsmanship.\n\nwww.youraster.com", client:"Aster", date:"11-22", gridRowSpan:34 },
    { id:50, cat:"reise",      title:"Vatican",             subtitle:"Travel",                 image:"assets/img/portfolio/juergen-nigg-vatican-st-peters-basilica-dome-perspective.jpg",               description:"St. Peter's Basilica seen through the iron lattice of the dome gallery. The baroque interior filtered through geometry — a frame within a frame, the sacred made abstract.", client:"Private Project", date:"09-23", gridRowSpan:42 },
    { id:51, cat:"reise",      title:"Rome",                subtitle:"Travel",                 image:"assets/img/portfolio/juergen-nigg-rome-villa-borghese-marble-statue-fountain.jpg",               description:"A marble goddess presides over a still fountain in Villa Borghese. Rome in its quieter register — green water, dark trees and the patient stone.", client:"Private Project", date:"09-23", gridRowSpan:36 },

    // ── SPORT / BEWEGUNG ─────────────────────────────────────

    { id:52, cat:"sport",      title:"Sequence",            subtitle:"Sports",                 image:"assets/img/portfolio/juergen-nigg-skiing-sequence-mount-blaser-tyrol.jpg",                       description:"Mount Blaser near Serles offered challenging freeride conditions — little snow, icy terrain, and difficult light. The camera position was never fixed; instead, both subject and camera remained in motion, making the movement itself an integral part of the work.", client:"Private Project", date:"03-21", gridRowSpan:32 },
    { id:53, cat:"sport",      title:"Joona",               subtitle:"Sports",                 image:"assets/img/portfolio/juergen-nigg-joona-kangas-skiing-nordkette-innsbruck.jpg",       description:"It's all about the shadows. Captured Joona Kangas at the Skyline Park Nordkette, using a 24mm lens to pull the viewer into the frame. Even on the smaller hits, the low sun and that leading shadow towards the bottom right create a massive sense of space. Geometry in the air.", client:"Private Project", date:"02-20", gridRowSpan:34 },
    { id:54, cat:"sport",      title:"Skier",               subtitle:"Sports · Portrait",      image:"assets/img/portfolio/juergen-nigg-skier-portrait-balaclava-white-minimal.jpg",         description:"A skier fully masked against the cold — balaclava, goggles, beanie — photographed against a white overcast sky. No background, no context. The athlete as anonymous form.", client:"Private Project", date:"01-19", gridRowSpan:32 },
    { id:55, cat:"artwork",    title:"Krimml Fluent",       subtitle:"Experimental",           image:"assets/img/portfolio/juergen-nigg-krimml-waterfall-panorama-experimental.jpg",              description:"A panoramic series of the Krimmler Wasserfälle compressed into a single frame — the waterfall at different moments, different exposures, different distances. Time made horizontal.", client:"Private Project", date:"09-21", gridRowSpan:30 },

];

if (typeof module !== 'undefined' && module.exports) {
    module.exports = portfolioItems;
}
