// ============================================================
// PORTFOLIO DATA – juergennigg.com  |  49 Werke
// Kategorien: art (6) | people (8) | documentary (14) | landscape (14) | sport (7)
// Reihenfolge: visueller Rhythmus — dunkel → B&W → kühl → warm → farbe → clean
// pos = CSS object-position für Thumbnail
// ============================================================

const portfolioItems = [

    // ── DARK OPENERS ────────────────────────────────────────
    { id:1,  cat:"landscape",    pos:"center 15%",   title:"Nockspitze Cross",    subtitle:"B&W · Night",           image:"assets/img/portfolio/juergen-nigg-nockspitze-summit-cross-night-fog-tyrol.jpg",       description:"Summit cross on the Nockspitze at night. Fog and moonlight conspire to erase the figure standing at its base — the shape barely human, barely there.", client:"Private Project", date:"07-21", gridRowSpan:44 },
    { id:2,  cat:"art",          pos:"center top",   title:"2ONE",                subtitle:"Artwork",                image:"assets/img/portfolio/juergen-nigg-artwork-2one-portrait-series.jpg",                   description:"A fierce Mouth - seductive Lips, attributes to be rich.\n\nThunderous - inverse to her tone, caught in a triangle of monochrome.\n\nStanding in blue, labeled - but not true. Naked below. a Human.\n\nVulnerable.\n\nSeries: Where do we go, where do we come from.\nPrint / Hahnemühle Fine Art Baryta / 60x90cm", client:"Private Project", date:"04-20", gridRowSpan:38 },
    { id:3,  cat:"people",       pos:"center 45%",   title:"Lips & Hat",          subtitle:"Portrait",               image:"assets/img/portfolio/juergen-nigg-portrait-hat-shadow-lowkey.jpg",                    description:"Studio portrait study in dramatic low key light. Hat, shadow, skin — reduced to the essential.", client:"Private Project", date:"04-22", gridRowSpan:40 },
    { id:4,  cat:"sport",        pos:"center center",title:"Minimal Laax",        subtitle:"Sports · Experimental",  image:"assets/img/portfolio/juergen-nigg-skiing-laax-bw-diptych-minimal.jpg",                description:"Two skiers, two worlds — day and night, positive and negative. A diptych compressed into one frame: one figure on white powder, one on absolute black.", client:"Private Project", date:"03-21", gridRowSpan:40 },
    { id:5,  cat:"art",          pos:"center 40%",   title:"Super(ri)or",         subtitle:"Artwork",                image:"assets/img/portfolio/juergen-nigg-artwork-superior-nature-bubbles.jpg",                description:"Imagine that we are just bubbles in an aquarium which try to reach the surface.\n\nNature's unwritten law is balance, nothing is superior.\n\nSeries: Where do we go, where do we come from.", client:"Private Project", date:"05-21", gridRowSpan:44 },
    { id:6,  cat:"art",          pos:"center top",   title:"Digital Distraction", subtitle:"Artwork",                image:"assets/img/portfolio/juergen-nigg-artwork-digital-distraction-series.jpg",             description:"Half way sick, but still hooked.\n\nThe digital revolution made it socially acceptable to be permanently distracted.\n\nWhat is real?\n\nSeries: Where do we go, where do we come from.\nPrint / Hahnemühle Fine Art Baryta / 50x75cm", client:"Private Project", date:"03-20", gridRowSpan:42 },
    { id:7,  cat:"sport",        pos:"center 30%",   title:"X-Games",             subtitle:"Sports",                 image:"assets/img/portfolio/juergen-nigg-xgames-norway-motox-corey-creed.jpg",               description:"At X-Games Norway — Corey Creed sends his bike soaring high enough to nearly meet the rooftop.", client:"Private", date:"08-19", gridRowSpan:36 },

    // ── B&W ZONE ────────────────────────────────────────────
    { id:8,  cat:"documentary",  pos:"center center",title:"Rock Silhouette",     subtitle:"B&W · Sardinia",         image:"assets/img/portfolio/juergen-nigg-sardinia-sea-stack-rock-silhouette-bw.jpg",         description:"A sea stack off the Sardinian coast reduced to pure form — black mass, white sky, silver water. Everything unnecessary removed. What remains is enough.", client:"Private Project", date:"09-23", gridRowSpan:30 },
    { id:9,  cat:"landscape",    pos:"center 30%",   title:"Wipptal",             subtitle:"B&W · Landscape",        image:"assets/img/portfolio/juergen-nigg-wipptal-winter-mountain-bw-tyrol-alps.jpg",         description:"A winter ascent in the Wipptal. The snowfield catches the angle of morning light and divides the frame — half shadow, half form.", client:"Private Project", date:"02-21", gridRowSpan:34 },
    { id:10, cat:"landscape",    pos:"center 25%",   title:"Rinnenspitze",        subtitle:"B&W · Landscape",        image:"assets/img/portfolio/juergen-nigg-habicht-north-face-clouds-bw-alps-tyrol.jpg",       description:"The north face of the Habicht. Clouds breach the ridge in a single powerful mass — the scale of the mountain readable only by the tiny snow couloirs.", client:"Private Project", date:"08-24", gridRowSpan:42 },
    { id:11, cat:"sport",        pos:"center 40%",   title:"Umbrella",            subtitle:"Sports · B&W",           image:"assets/img/portfolio/juergen-nigg-krimml-waterfall-umbrella-bw-austria.jpg",          description:"Two people shelter beneath an umbrella at the base of the Krimmler Wasserfälle. The waterfall spray fills the sky — a wall of white noise, of water becoming air.", client:"Private Project", date:"09-21", gridRowSpan:40 },
    { id:12, cat:"landscape",    pos:"center 28%",   title:"Nockspitze Moon",     subtitle:"B&W · Night",            image:"assets/img/portfolio/juergen-nigg-nockspitze-mountain-moon-night-bw-stars.jpg",       description:"Full moon over the Nockspitze ridge. Clouds stream past the summit in long exposure — the mountain silhouette sharp against a brightened sky.", client:"Private Project", date:"07-21", gridRowSpan:38 },
    { id:13, cat:"landscape",    pos:"center 35%",   title:"CrankIt Mountains",   subtitle:"B&W · Landscape",        image:"assets/img/portfolio/juergen-nigg-zugspitze-storm-clouds-mountain-bw.jpg",            description:"Storm light over the Zugspitz massif. The clouds press down on the peaks and a ray of sun cuts through — the Alps in their most dramatic mood.", client:"Private Project", date:"04-19", gridRowSpan:36 },
    { id:14, cat:"documentary",  pos:"center center",title:"Venice Canal",        subtitle:"B&W · Travel",           image:"assets/img/portfolio/juergen-nigg-venice-grand-canal-bridge-silhouette-bw.jpg",       description:"A Grand Canal bridge reduced to silhouette at dusk. The water carries the last light between the buildings.", client:"Private Project", date:"06-22", gridRowSpan:36 },
    { id:15, cat:"sport",        pos:"center 42%",   title:"Ski B&W",             subtitle:"Sports",                 image:"assets/img/portfolio/juergen-nigg-freeride-skiing-powder-bw-alps.jpg",                description:"High-speed turn through a steep mogul field. Snow explodes upward — the skier's form compressed into the moment before the next drop.", client:"Private Project", date:"04-25", gridRowSpan:38 },
    { id:16, cat:"art",          pos:"center top",   title:"Prejudice",           subtitle:"Artwork",                image:"assets/img/portfolio/juergen-nigg-artwork-prejudice-portrait-series.jpg",             description:"We learn - we judge.\n\nCan you hear, the voice inside?\n\nThat's trust been taken, and prejudice awaken.\n\nSeries: Where do we go, where do we come from.", client:"Private Project", date:"03-21", gridRowSpan:36 },

    // ── COOL BLUE ───────────────────────────────────────────
    { id:17, cat:"documentary",  pos:"center 50%",   title:"Malta",               subtitle:"Travel",                 image:"assets/img/portfolio/juergen-nigg-malta-blue-hour-cityscape-long-exposure.jpg",       description:"Blue hour in Malta. Capturing the city's golden lights as they bleed into the deep indigo of the Mediterranean.", client:"Private Project", date:"11-17", gridRowSpan:30 },
    { id:18, cat:"documentary",  pos:"center 55%",   title:"Achensee",            subtitle:"Aerial · Travel",        image:"assets/img/portfolio/juergen-nigg-achensee-aerial-sailing-boats-tyrol.jpg",           description:"Achensee from altitude. Sailboats scattered across deep emerald water like brushstrokes — the campsite and forest below sharply real, the lake an abstraction of colour.", client:"Private Project", date:"08-20", gridRowSpan:38 },
    { id:19, cat:"documentary",  pos:"center 60%",   title:"Paraglider",          subtitle:"Aerial · Travel",        image:"assets/img/portfolio/juergen-nigg-paraglider-achensee-aerial-tyrol-austria.jpg",      description:"From the summit of Rotspitze, looking straight down onto the turquoise shallows of Achensee. A paraglider traces a slow arc above the water.", client:"Private Project", date:"08-20", gridRowSpan:40 },
    { id:20, cat:"art",          pos:"center 50%",   title:"Biennale Neon",       subtitle:"Art · Venice",           image:"assets/img/portfolio/juergen-nigg-venice-biennale-neon-wire-installation.jpg",        description:"An installation at the Venice Biennale — blue neon wire suspended in stacked geometric planes. Architecture as suggestion, space as medium.", client:"Private Project", date:"06-22", gridRowSpan:36 },

    // ── WARM GOLDEN ─────────────────────────────────────────
    { id:21, cat:"landscape",    pos:"center 50%",   title:"Salfeins Lake",       subtitle:"Landscape",              image:"assets/img/portfolio/juergen-nigg-salfeins-alpine-lake-sunset-reflection-tyrol.jpg",  description:"Last light at the high alpine lake above Salfeins. A lone signpost stands in silhouette at the water's edge — its reflection perfect in the still surface.", client:"Private Project", date:"09-25", gridRowSpan:36 },
    { id:22, cat:"landscape",    pos:"25% 45%",      title:"Salfeins Overlook",   subtitle:"Landscape",              image:"assets/img/portfolio/juergen-nigg-salfeins-innsbruck-valley-sunset-silhouette.jpg",   description:"Sunset from the ridge above Salfeins. A figure stands on the last rock before the world drops away into the Inn valley and Innsbruck below.", client:"Private Project", date:"09-25", gridRowSpan:38 },
    { id:23, cat:"landscape",    pos:"center 55%",   title:"Sardinia Sunset",     subtitle:"Landscape",              image:"assets/img/portfolio/juergen-nigg-sardinia-coastal-sunset-silhouette.jpg",            description:"The last light dissolves into the Sardinian coastline. Silhouettes of rock and pine frame the glowing horizon.", client:"Private Project", date:"09-23", gridRowSpan:32 },
    { id:24, cat:"landscape",    pos:"center 45%",   title:"Father & Son",        subtitle:"Experimental",           image:"assets/img/portfolio/juergen-nigg-father-son-tree-sunset-minimal.jpg",                description:"Two trees of different sizes in front of a sunset. The larger tree represents a father's guiding presence — standing behind the smaller tree not to shield it, but to support it.", client:"Private Project", date:"01-21", gridRowSpan:34 },
    { id:25, cat:"documentary",  pos:"center 40%",   title:"Sardinia Summit",     subtitle:"Travel",                 image:"assets/img/portfolio/juergen-nigg-sardinia-mountain-summit-golden-hour.jpg",          description:"First light on the summit ridge above the Gallura coast. Ancient rock, worn stone steps and a brass instrument surveying the sea.", client:"Private Project", date:"09-23", gridRowSpan:36 },
    { id:26, cat:"people",       pos:"center 50%",   title:"Ethiopia Watcher",    subtitle:"Documentary",            image:"assets/img/portfolio/juergen-nigg-ethiopia-highlands-morning-landscape-watcher.jpg",  description:"Early morning on the Ethiopian highlands. A lone figure crouched against the vast horizon — the moment before the mist lifts.", client:"Private Project", date:"11-18", gridRowSpan:34 },
    { id:27, cat:"sport",        pos:"center 35%",   title:"CrankIt",             subtitle:"Sports",                 image:"assets/img/portfolio/juergen-nigg-crankit-skiing-park-ehrwald-tyrol.jpg",             description:"Lucas Mangold's gathering in Ehrwald to celebrate the soul of skiing. Crank It to the max — good people, easy vibes, pure park shredding.", client:"Private Project", date:"04-19", gridRowSpan:30 },

    // ── EARTH / DOCUMENTARY ─────────────────────────────────
    { id:28, cat:"people",       pos:"center 40%",   title:"Ranger",              subtitle:"Documentary",            image:"assets/img/portfolio/juergen-nigg-ethiopia-simien-mountains-ranger.jpg",              description:"On the rugged precipice of Ethiopia's Simien Mountains, a local ranger stands sentinel — a silent guardian of one of Africa's most dramatic landscapes.", client:"Private Project", date:"11-18", gridRowSpan:36 },
    { id:29, cat:"landscape",    pos:"center 40%",   title:"Ethiopia",            subtitle:"Landscape",              image:"assets/img/portfolio/juergen-nigg-ethiopia-simien-mountains-cloud-forest.jpg",        description:"Deep in the Simien Mountains highlands, the world disappears into a thick, rolling fog. The ancient trees are draped in heavy layers of hanging moss.", client:"Private Project", date:"04-19", gridRowSpan:36 },
    { id:30, cat:"landscape",    pos:"center 40%",   title:"Sardinia Cliffs",     subtitle:"Landscape",              image:"assets/img/portfolio/juergen-nigg-sardinia-capo-caccia-cliffs-blue-sea.jpg",          description:"Looking down the spine of Capo Caccia from the ridge trail. Deep cobalt sea, white limestone and the rust-red soil of the path.", client:"Private Project", date:"09-23", gridRowSpan:40 },
    { id:31, cat:"documentary",  pos:"center center",title:"Building Bridges",    subtitle:"Travel",                 image:"assets/img/portfolio/juergen-nigg-venice-building-bridges-quinn-sculpture.jpg",       description:"Looking up at Lorenzo Quinn's 'Building Bridges' from the waterline of the Arsenale. Each arch represents a core value — Friendship, Wisdom, Help, Faith, Hope, and Love.", client:"Private Project", date:"10-19", gridRowSpan:34 },
    { id:32, cat:"documentary",  pos:"center 45%",   title:"Sunrise",             subtitle:"Travel",                 image:"assets/img/portfolio/juergen-nigg-sardinia-caprera-lighthouse-sunrise.jpg",           description:"While exploring Sardinia in 2023, I captured a sunrise that lined up perfectly with the lighthouse on Isolotto di Barrettini.", client:"Private Project", date:"09-23", gridRowSpan:30 },
    { id:33, cat:"landscape",    pos:"center 42%",   title:"Riezer Reflection",   subtitle:"Alps · Austria",         image:"assets/img/portfolio/juergen-nigg-riezerferner-alpine-lake-reflection-autumn.jpg",    description:"A perfect mirror at the high alpine lake on Riezerferner. The mountain reflected in still water, autumn grass at the water's edge.", client:"Private Project", date:"10-24", gridRowSpan:34 },
    { id:34, cat:"documentary",  pos:"center 65%",   title:"Swan",                subtitle:"Documentary",            image:"assets/img/portfolio/juergen-nigg-swan-rusty-bridge-pier-gdansk-poland.jpg",          description:"A white swan glides beneath the rusted skeleton of an abandoned bridge pier. Grace and decay — an unremarkable scene that reveals itself only to those who stop.", client:"Private Project", date:"08-24", gridRowSpan:42 },
    { id:35, cat:"art",          pos:"center 50%",   title:"Written by Water",    subtitle:"Art · Venice",           image:"assets/img/portfolio/juergen-nigg-venice-biennale-paper-archive-light.jpg",           description:"Thousands of documents cover the floor of a darkened pavilion at the Venice Biennale. A single shaft of light enters from above — the archive breathing, the past made present.", client:"Private Project", date:"06-22", gridRowSpan:38 },

    // ── COLOUR / VIBRANT ────────────────────────────────────
    { id:36, cat:"people",       pos:"center 18%",   title:"Portrait Colour",     subtitle:"Portrait",               image:"assets/img/portfolio/juergen-nigg-portrait-colour-paint-ethiopia.jpg",              description:"Identity, colour and intensity. Face paint meets Ethiopian textile tradition in a raw, unfiltered moment of presence.", client:"Private Project", date:"06-19", gridRowSpan:42 },
    { id:37, cat:"documentary",  pos:"center 50%",   title:"Burano Ladder",       subtitle:"Travel",                 image:"assets/img/portfolio/juergen-nigg-burano-venice-colourful-facade-ladder.jpg",        description:"Geometry and colour in a Burano side alley. A moment of stillness caught between fading paint, a leaning ladder and a woman resting in the shade.", client:"Private Project", date:"06-22", gridRowSpan:38 },
    { id:38, cat:"documentary",  pos:"center 40%",   title:"Burano",              subtitle:"Travel",                 image:"assets/img/portfolio/juergen-nigg-burano-venice-pink-minimal-travel.jpg",            description:"Known for its exquisite lace craftsmanship and vibrant, colorful houses, Burano is a must-visit when traveling to Venice.", client:"Private Project", date:"06-22", gridRowSpan:32 },
    { id:39, cat:"landscape",    pos:"center 38%",   title:"Autumn",              subtitle:"Urban · Landscape",      image:"assets/img/portfolio/juergen-nigg-innsbruck-autumn-virginia-creeper-villa.jpg",       description:"An Innsbruck villa smothered in Virginia creeper at peak colour. Through the black branches a single window holds the light.", client:"Private Project", date:"10-21", gridRowSpan:36 },
    { id:40, cat:"documentary",  pos:"center center",title:"Carousel",            subtitle:"Documentary",            image:"assets/img/portfolio/juergen-nigg-carousel-long-exposure-night-gdansk.jpg",          description:"Long-exposure of a fairground carousel in Gdańsk at night. Light trails spiral outward from the hub — the ride long finished, its movement preserved in gold.", client:"Private Project", date:"08-24", gridRowSpan:38 },

    // ── PEOPLE / FASHION ────────────────────────────────────
    { id:41, cat:"people",       pos:"center 28%",   title:"Inn Beach",           subtitle:"Fashion",                image:"assets/img/portfolio/juergen-nigg-aster-leather-bag-inn-river-innsbruck.jpg",        description:"Aster Leather Bags at the banks of the Inn river. The Burgundy tote against alpine light — a study in contrast between urban craft and natural setting.", client:"Aster", date:"04-24", gridRowSpan:40 },
    { id:42, cat:"people",       pos:"center 22%",   title:"Jungle Fever",        subtitle:"Fashion",                image:"assets/img/portfolio/juergen-nigg-aster-jungle-fever-botanical-garden.jpg",          description:"Sabrina Huber for Aster Leather Bags in the botanical gardens. The 'Biggie' in Creme, styled against a bold camouflage dress.", client:"Aster", date:"08-22", gridRowSpan:40 },
    { id:43, cat:"documentary",  pos:"center 35%",   title:"Sardinia Column",     subtitle:"Travel",                 image:"assets/img/portfolio/juergen-nigg-sardinia-roman-column-sailboat-sea.jpg",           description:"An ancient Roman column stands alone against the Sardinian sky. A single sailboat crosses the horizon — past and present sharing the same sea.", client:"Private Project", date:"09-23", gridRowSpan:38 },
    { id:44, cat:"people",       pos:"center 18%",   title:"Studio",              subtitle:"Fashion",                image:"assets/img/portfolio/juergen-nigg-aster-studio-fashion-portrait.jpg",                description:"Verena Pötzl x Aster Leather Bags. A professional studio shoot highlighting the elegance of everyday utility.\n\nDiscover the range at YourAster.com", client:"Aster", date:"06-23", gridRowSpan:38 },
    { id:45, cat:"people",       pos:"center 28%",   title:"Aster",               subtitle:"Fashion",                image:"assets/img/portfolio/juergen-nigg-aster-leather-bag-fashion-commercial.jpg",         description:"Your Aster is a brand dedicated to handcrafted leather bags made in Ethiopia. Strong commitment to a fair and transparent supply chain.\n\nwww.youraster.com", client:"Aster", date:"11-22", gridRowSpan:34 },
    { id:46, cat:"documentary",  pos:"center 28%",   title:"Vatican",             subtitle:"Travel",                 image:"assets/img/portfolio/juergen-nigg-vatican-st-peters-basilica-dome-perspective.jpg",  description:"St. Peter's Basilica seen through the iron lattice of the dome gallery. The baroque interior filtered through geometry — a frame within a frame.", client:"Private Project", date:"09-23", gridRowSpan:42 },
    { id:47, cat:"documentary",  pos:"center 40%",   title:"Rome",                subtitle:"Travel",                 image:"assets/img/portfolio/juergen-nigg-rome-villa-borghese-marble-statue-fountain.jpg",   description:"A marble goddess presides over a still fountain in Villa Borghese. Rome in its quieter register — green water, dark trees and the patient stone.", client:"Private Project", date:"09-23", gridRowSpan:36 },

    // ── SPORT / CLOSE ───────────────────────────────────────
    { id:48, cat:"sport",        pos:"center center",title:"Sequence",            subtitle:"Sports",                 image:"assets/img/portfolio/juergen-nigg-skiing-sequence-mount-blaser-tyrol.jpg",           description:"Mount Blaser near Serles — little snow, icy terrain, difficult light. Both subject and camera in motion, making the movement itself an integral part of the work.", client:"Private Project", date:"03-21", gridRowSpan:32 },
    { id:49, cat:"sport",        pos:"center 35%",   title:"Joona",               subtitle:"Sports",                 image:"assets/img/portfolio/juergen-nigg-joona-kangas-skiing-nordkette-innsbruck.jpg",      description:"It's all about the shadows. Joona Kangas at the Skyline Park Nordkette. The low sun and leading shadow create a massive sense of space.", client:"Private Project", date:"02-20", gridRowSpan:34 },

];

if (typeof module !== 'undefined' && module.exports) { module.exports = portfolioItems; }
