const wallpapers = [
    { id:1,  title:"Ethiopia Highlands I",  subtitle:"Travel · Ethiopia",   file:"jn-ethiopia-highlands-landscape-2k.jpg",    format:"landscape", resolution:"2K", dimensions:"2160 × 1440" },
    { id:2,  title:"Ethiopia Highlands II", subtitle:"Travel · Ethiopia",   file:"jn-ethiopia-highlands-ii-landscape-2k.jpg", format:"landscape", resolution:"2K", dimensions:"2160 × 1440" },
    { id:3,  title:"Ethiopia Woods",        subtitle:"Travel · Ethiopia",   file:"jn-ethiopia-woods-landscape-2k.jpg",        format:"landscape", resolution:"2K", dimensions:"2160 × 1440" },
    { id:4,  title:"Innsbruck Night",       subtitle:"Night · Austria",     file:"jn-innsbruck-night-landscape-2k.jpg",       format:"landscape", resolution:"2K", dimensions:"2160 × 1440" },
    { id:5,  title:"Building Bridges",      subtitle:"Travel · Venice",     file:"jn-building-bridges-landscape-2k.jpg",      format:"landscape", resolution:"2K", dimensions:"2160 × 1440" },
    { id:6,  title:"Clouds",                subtitle:"B&W · Landscape",     file:"jn-clouds-landscape-2k.jpg",               format:"landscape", resolution:"2K", dimensions:"2160 × 1440" },
    { id:7,  title:"Minimal",               subtitle:"B&W · Silhouette",    file:"jn-minimal-landscape-2k.jpg",              format:"landscape", resolution:"2K", dimensions:"2160 × 1440" },
    { id:8,  title:"Life",                  subtitle:"Minimal · Nature",    file:"jn-life-landscape-2k.jpg",                 format:"landscape", resolution:"2K", dimensions:"2160 × 1440" },
    { id:9,  title:"Illusion",              subtitle:"Aerial · Abstract",   file:"jn-illusion-landscape-2k.jpg",             format:"landscape", resolution:"2K", dimensions:"2160 × 1440" },
    { id:10, title:"Palm",                  subtitle:"Experimental · Color",file:"jn-palm-landscape-2k.jpg",                 format:"landscape", resolution:"2K", dimensions:"2160 × 1440" },
    { id:11, title:"Waves",                 subtitle:"Statement · Abstract",file:"jn-waves-landscape-2k.jpg",                format:"landscape", resolution:"2K", dimensions:"2160 × 1440" },
    { id:12, title:"Burano Pink",           subtitle:"Minimal · Burano",    file:"jn-burano-pink-portrait-2k.jpg",           format:"portrait",  resolution:"2K", dimensions:"1441 × 2160" },
    { id:13, title:"Burano Red",            subtitle:"Minimal · Burano",    file:"jn-burano-red-portrait-2k.jpg",            format:"portrait",  resolution:"2K", dimensions:"1441 × 2160" },
    { id:14, title:"Burano Yellow",         subtitle:"Minimal · Burano",    file:"jn-burano-yellow-portrait-2k.jpg",         format:"portrait",  resolution:"2K", dimensions:"1441 × 2160" },
    { id:15, title:"Malta Split",           subtitle:"Statement · Malta",      file:"jn-malta-split-panorama-8k.jpg",           format:"panorama",  resolution:"8K", dimensions:"8000 × 3428" },
    { id:16, title:"Bird",                  subtitle:"B&W · Wildlife",         file:"jn-bird-bw-landscape-2k.jpg",              format:"landscape", resolution:"2K", dimensions:"2160 × 1440" },
    { id:17, title:"Colour",                subtitle:"Sunset · Landscape",     file:"jn-colour-sunset-landscape-2k.jpg",        format:"landscape", resolution:"2K", dimensions:"2160 × 1440" },
    { id:18, title:"Sardinia Sunset",       subtitle:"Travel · Sardinia",      file:"jn-sardinia-sunset-landscape-2k.jpg",      format:"landscape", resolution:"2K", dimensions:"2160 × 1440" },
    { id:19, title:"Sardinia Ocean",        subtitle:"Travel · Sardinia",      file:"jn-sardinia-ocean-landscape-2k.jpg",       format:"landscape", resolution:"2K", dimensions:"2160 × 1440" },
    { id:20, title:"Sardinia Sky I",        subtitle:"Travel · Sardinia",      file:"jn-sardinia-sky-i-landscape-2k.jpg",       format:"landscape", resolution:"2K", dimensions:"2160 × 1440" },
    { id:21, title:"Sardinia Sky II",       subtitle:"Travel · Sardinia",      file:"jn-sardinia-sky-ii-landscape-2k.jpg",      format:"landscape", resolution:"2K", dimensions:"2160 × 1440" },
    { id:22, title:"Sardinia Sky III",      subtitle:"Travel · Sardinia",      file:"jn-sardinia-sky-iii-landscape-2k.jpg",     format:"landscape", resolution:"2K", dimensions:"2160 × 1440" },
];
